[package]
name = "sforce"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.14", features = ["wav"] }
image = "0.24"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
